name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/**
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-24.04"
    permissions:
      packages: write
      repository-projects: write
      contents: write
      id-token: write
    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/setup-java@v4"
        with:
          java-version: "21"
          distribution: "temurin"
      - name: "Cache gradle wrapper"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: "Cache Gradle packages"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: "Build and tests"
        run: ./gradlew test build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: x-access-token
      - name: "Upload reports"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'test-reports'
          path: '**/build/reports/**'
