name: "Publish emottak-utils library"
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-24.04"
    permissions: 
        packages: write
        repository-projects: write
        contents: write
    steps:
    - uses: "actions/checkout@v5"
    - uses: "actions/setup-java@v5"
      with:
        "java-version": "21"
        "distribution": "temurin"
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: "Build and tests"
      run: ./gradlew test build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: x-access-token
    - name: Publish emottak-utils
      run: ./gradlew --stacktrace publish
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: x-access-token
